language: C
before_install: 
- sudo apt-get update -qq
- wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
- chmod +x ./install-tl-ubuntu
- wget -O linux.profile https://gist.githubusercontent.com/helloIAmPau/f1f6d90a9aadd514ef1d/raw/63e98508673003ac0509b2e7f5759a4b1e7afff3/linux.profile
- sudo ./install-tl-ubuntu -p linux.profile --no-link-ubuntu --repository http://ctan.mirror.garr.it/mirrors/CTAN/
- ls /home/travis/build/helloIAmPau/curriculum-vitae/tl/bin/x86_64-linux/
- export PATH="$PATH:/home/travis/build/helloIAmPau/curriculum-vitae/tl/bin/x86_64-linux/"
script: make deploy
after_success: 
- cd out/
- git init
- git config user.name ${GIT_NAME}
- git config user.email ${GIT_EMAIL}
- git add .
- git commit -m 'deploying an updated version of my cv'
- git push --force --quiet https://${GH_TOKEN}@${GH_URL} master:gh-pages > /dev/null 2>&1
env: 
  global: 
  - GH_URL="github.com/helloIAmPau/curriculum-vitae"
  - secure: a0is0Kpdbm3G171t5OUj9rc4Pyl4cn0eHsEau7Oj8BPpY28l5avnHEYaM3NN4+jD3OeL6npMsNG9IkstMAimbaU1cwAryk35D6N0Vfh5MYxk/I3dWLT5mcv7nZ66kQSKCVpco5A+KW28mo9at2g1DrQFrlgAsO4r5CV9HuWCIg8=
  - secure: h2GqrziyNhuXem0EtdUGo6FlcU8HH9ij4HWw7k1XSTbAHI/pW4yYXBoJGuEVfMuTyzoyWG5TfenROiYrnC3z4CPnBTaljisuBLpb0SpgkonBGW9m6RsgRlHbIRbKfJ3nOQGF4BN/gQxHNPXM5vzQSo8ddiiV/EOdZizC8cqxF+E=
  - secure: f/w20pB67TeKzlyy3b7qKLR9c13CBp36sbT/wtlhstICkZF8bDHPEQV85xsf+Jk1OrsEaNsm9/3+AbYMeDe3oJFQ0iOtzuh1eFMS3ZA6IQHS5XHHO3ok03updGgy1rwOj+TMEyfcxyf3GIYr+HBo8pFu4+p0kcUUPUa6CxM6xDU=
