language: C
before_install: 
  - sudo apt-get update -qq
  - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu
  - chmod +x ./install-tl-ubuntu
  - sudo ./install-tl-ubuntu
script: make deploy
after_success: 
  - cd out/
  - git init
  - git config user.name ${GIT_NAME}
  - git config user.email ${GIT_EMAIL}
  - git add .
  - git commit -m 'deploying updated version of my cv'
  - git push --force --quiet https://${GH_TOKEN}@${GH_URL} master:gh-pages > /dev/null 2>&1
env: 
  global: 
  - secure: eGV8naQfKSF1JJZoT9oKJsFfRFZ8lq2wQdt6NoTYbq4KlEo2+5vGeu5uAxz8HTgMRvu2ZlNqsO6q5pB2g/hip158S0kUv2L34y/avrGjLESwL5/hFcPC5MhhshSqVQcRKRt1SnuRwrPjwR4zpqGkCfilXNBl/gTo4Jw/m+ov9m8=
  - secure: hUUTGTU/CX3ii5BMNtm28D32Qk7P3ibwQeCb9caygY4X//jXM3Use1EFrA7wLfW+43NgeESO/YegYRO1QPKmC7KSRhjydwBbd2DNqXjp5zB5+lp0utsnAA13ZWVl66vClMnUTRQEt4+z042KQ3vkQL+Rr1vuTiQPJr89Zt+GM5o=
  - secure: LAlRhIowmH7pFQGfQov0W2XDksCQPzCt6TuhU4qDYohd0Yel239rHgHsJpS7tRZObApEd7H8c0MqK8qn+aewj5x4E2y84H2tZx8vnRJq1R1jEf6e5FZ/kM6kGqvK/qANOQK+eHSheOhYk/eo6kejcQo1udMeIOML0HeD1QuCnes=
  - GH_URL="github.com/helloIAmPau/curriculum-vitae"
  - secure: hOn7FiC75W4zIE4ttG8tjkuObk3FsKQ1WRBss5+rG8fRDf3wzcO/kwImnLJZVFuCBhsR3xkAiCVdGCWJNdOY+wm+bmzUqV0YhXV/jiu+Ax2MAfbSR46ctx38chmEUHAiCJh2sH0A+Z1nH25HLMyvSjCAbTwNuyrStfiR0Z4VBLs=
